name: ETCetera            # default is root
channels:
- defaults
- conda-forge
dependencies:         # everything under this, installed by conda
- python=3.8
- pip
- sympy=1.6.2
- numpy=1.19.2
- setuptools=50.3.0
- future=0.18.2
- scipy=1.5.2
- numba=0.51.2
- cvxpy=1.1.5
- control=0.8.3
- matplotlib=3.3.2
- tqdm=4.50.0
- joblib=0.16.0
- python-igraph
- NetworkX
- pyparsing
- cycler
- python-dateutil
#- kiwisolver
- shortuuid
- pygraphviz
- graph-tool
- pip:                # everything under this, installed by pip
  - pycddlib
  - z3-solver~=4.8.9.0
  - dd >= 0.1.1 --install-option="--fetch" --install-option="--cudd"
